import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UniversityService {

  constructor() { }
  universities=[
    'Ain Shams University',
    'Al-Azhar University',
    'Alexandria University',
    'Assiut University',
    'Aswan University',
    'Banha University',
    'Beni-Suef University',
    'Cairo University',
    'Damanhour University',
    'Damietta University',
    'Egypt-Japan University of Science and Technology',
    'Fayoum University',
    'Helwan University',
    'Institute of Aviation Engineering and Technology',
    'Mansoura University',
    'Kafrelsheikh University',
    'Military Technical College',
    'Minia University',
    'Minufiya University',
    'Port Said University',
    'Sadat Academy for Management Sciences',
    'Sohag University',
    'South Valley University',
    'Suez Canal University',
    'Suez University',
    'Tanta University',
    'University of Sadat City',
    'University of Science and Technology at Zewail City',
    'Zagazig University',
    'Ahram Canadian University',
    'Alamein University',
    'Alexandria Higher Institute of Engineering and Technology',
    'American University in Cairo',
    'Arab Academy for Science, Technology and Maritime Transport',
    'Arab Open University',
    'British University In Egypt',
    'Cairo Higher Institute for Engineering, Computer Science & Management',
    'Cairo Private Technology Institute',
    'Canadian International College',
    'Culture & Science City',
    'Delta University for Science and Technology',
    'Egyptian Chinese University',
    'Egyptian e-Learning University',
    'Egyptian Russian University',
    'El Asher University',
    'El Shorouk Academy',
    'Future Academy',
    'Future University in Egypt',
    'German University in Cairo',
    'Heliopolis University',
    'Higher Institute for Engineering and Technology in Kafr Elsheikh',
    'Higher Technological Institute',
    'International Academy for Engineering & Media Sciences',
    'Mansoura High Institute for Engineering and Technology (Mansoura College Academy)',
    'Misr Higher Institute For Engineering And Technology in Mansoura',
    'Misr International University',
    'Misr University for Science and Technology',
    'Modern Academy For Engineering & Technology',
    'Modern Academy In Maadi',
    'Modern Sciences and Arts University',
    'Modern University for Technology and Information',
    'MTI University',
    'Nahda University',
    'Nile University',
    'October 6 University (O6U)',
    'Pharos University In Alexandria',
    'Science Valley Academy',
    'Sinai University',
    'Thebes Academy',
    'French University of Egypt',
    'Badr University in Cairo',
    'New Cairo Academy',
    'Akhbar elyom academy',
    'New Giza University',
  ];
  getuniversity(){
    return this.universities.sort();
  }
}
