//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int UserId { get; set; }
        public int CorporateId { get; set; }
        public int JobFormId { get; set; }
        public int UserAnswerId { get; set; }
        public Nullable<int> JobApplyStatusId { get; set; }
    
        public virtual Corporates Corporates { get; set; }
        public virtual JobForm JobForm { get; set; }
        public virtual UserAnswers UserAnswers { get; set; }
        public virtual Users Users { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual JobApplianceStatus JobApplianceStatus { get; set; }
    }
}
