//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public string Duration { get; set; }
        public int ContactPhoneNumber { get; set; }
        public string ContactEmail { get; set; }
        public string Language { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual JobTypes JobTypes { get; set; }
    }
}
