//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.JobApply = new HashSet<JobApply>();
            this.JobForm = new HashSet<JobForm>();
            this.Requirements = new HashSet<Requirements>();
        }
    
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal Salary { get; set; }
        public bool DisplaySalary { get; set; }
        public int CityId { get; set; }
        public int CountryId { get; set; }
        public int YearsOFExpertiseId { get; set; }
        public int CorporateId { get; set; }
        public Nullable<int> AreaOfExpertiseId { get; set; }
    
        public virtual AreaOfExpertise AreaOfExpertise { get; set; }
        public virtual City City { get; set; }
        public virtual Corporates Corporates { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApply> JobApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobForm> JobForm { get; set; }
        public virtual YearsOfExperience YearsOfExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirements> Requirements { get; set; }
    }
}
