//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NGODBEntities : DbContext
    {
        public NGODBEntities()
            : base("name=NGODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaOfExpertise> AreaOfExpertise { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Corporates> Corporates { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<JobApplianceStatus> JobApplianceStatus { get; set; }
        public virtual DbSet<JobApply> JobApply { get; set; }
        public virtual DbSet<JobForm> JobForm { get; set; }
        public virtual DbSet<QuestionsChoices> QuestionsChoices { get; set; }
        public virtual DbSet<Segments> Segments { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<UserAnswers> UserAnswers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSkills> UserSkills { get; set; }
        public virtual DbSet<YearsOfExperience> YearsOfExperience { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Requirements> Requirements { get; set; }
    }
}
