//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirements
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public string Requirements1 { get; set; }
    
        public virtual Jobs Jobs { get; set; }
    }
}
