//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int Id { get; set; }
        public string SkillsName { get; set; }
        public int AreaOfExpertiseId { get; set; }
    
        public virtual AreaOfExpertise AreaOfExpertise { get; set; }
    }
}
