//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrivileges
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int PrivilegesId { get; set; }
    
        public virtual Privileges Privileges { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
