//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace last.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventposting
    {
        public int Id { get; set; }
        public string TicketLink { get; set; }
        public string EventName { get; set; }
        public string EventDate { get; set; }
        public string EventDescription { get; set; }
        public string EventHeadline { get; set; }
        public int JobTypeId { get; set; }
        public int CitiesId { get; set; }
        public int CountryId { get; set; }
    }
}
