//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace last.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobReference
    {
        public int Id { get; set; }
        public string Ref_Name { get; set; }
        public Nullable<int> JobTypeId { get; set; }
    
        public virtual JobType JobType { get; set; }
    }
}
